### ISSUE TITLE
Check early for missing sudo

### ISSUE THREAD

**Issue by krlmlr** [gaborcsardi/rim#26]
Ideally before downloading. Otherwise, I need to wait for the download before I see the error message.

**Comment by gaborcsardi** [comment]
This is fixed in `dev`: https://github.com/gaborcsardi/rim/blob/dev/src/macos.rs#L31

**Comment by gadenbuie** [comment]
Is `sudo` expected or required for MacOS, or should `rim add` be able to work without `sudo`?

**Comment by gaborcsardi** [comment]
You need sudo for non-interactive install from the command line.

**Comment by gadenbuie** [comment]
I think you're saying that installing R from the command line without a GUI requires sudo, did I understand correctly? Which would explain why I'd need to `sudo rim add 4.1.2`. If that's the case, it'd be good to document this in the README; having to unexpectedly add sudo is usually a cause for concern.

**Comment by gaborcsardi** [comment]
Now it looks like this:
```
❯ rim add 3.3
Sorry, rim needs your password for this.
Password:
Downloading https://cloud.r-project.org/bin/macosx/old/R-3.3.3.pkg ->
    /tmp/rim/x86_64-R-3.3.3.pkg
^C
```

So you don't need to add the `sudo` before, rim will ask for your password later. 

It could have more details why the password is needed. but is it really surprising that you need to type in your password? There is no way to install R on macOS without password, command like or GUI.

**Comment by gadenbuie** [comment]
That's nice and I don't think more details are needed. The surprise isn't that my password is required. The surprise is that the docs said I could call `rim add 4.1.2` but the command fails without sudo (well, used to fail). In many other cases, e.g. `npm`, needing sudo is indicative of a local permissions or installation problem.

**Comment by gaborcsardi** [comment]
It looks like this now:
```
❯ ./target/debug/rim add devel
Running `sudo` for adding new R versions. This might need your password.
Password:

❯ ./target/debug/rim system fix-permissions
Running `sudo` for changing system library permissions. This might need your password.
Password:
```

`sudo` might be a bit too technical, but overall it is much better I think.

**Comment by krlmlr** [comment]
Works as advertised, thank you!
